[package]
name = "rusty-puff"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
bm25 = { version = "2.3.2", features = ["parallelism"] }
futures-util = "0.3.31"
iced = { version = "0.14", features = ["tokio"] }
lazy_static = "1.5.0"
ollama-rs = { version = "0.3.3", features = ["stream"] }
reqwest = { version = "0.12.26", features = ["json", "rustls-tls", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio-stream = "0.1.17"
