[package]
name = "rusty-puff"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
iced = { version = "0.14", features = ["tokio"] }
ollama-rs = { version = "0.3.3", features = ["stream"] }
tokio-stream = "0.1.17"
